version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  add_data_consumer:
    build:
      context: ./add_data
    container_name: add_data_consumer
    depends_on:
      - rabbitmq

  fastapi_app:
    build:
      context: ./app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  mongo_data:
